[POLYLINE]
Type=0x2a
Label=Granica strefy ekonomicznej Holandia - Wielka Brytania
EndLevel=3
Data0=(51.94000,2.59137),(51.98333,2.62667),(52.01667,2.65833),(52.08833,2.70333),(52.10000,2.71500),(52.20000,2.83218)
Plik=narzedzia/granice.txt
[END]

; granica na mapie Rotterdam NL - Belgia BE
[POLYLINE]
Type=0x2a
Label=Granica strefy ekonomicznej Belgia - Holandia
EndLevel=3
Data0=(51.70000,2.83357),(51.87611,2.53933)
Plik=narzedzia/granice.txt
[END]