//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from x:/source/Antlr/FrasMaciej/AntlerUniversityProject/Maps/Maps/GetUMPStx.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="GetUMPStx"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IGetUMPStxVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="GetUMPStx.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile([NotNull] GetUMPStx.FileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GetUMPStx.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSection([NotNull] GetUMPStx.SectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GetUMPStx.polygon_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPolygon_section([NotNull] GetUMPStx.Polygon_sectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GetUMPStx.polyline_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPolyline_section([NotNull] GetUMPStx.Polyline_sectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GetUMPStx.poi_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPoi_section([NotNull] GetUMPStx.Poi_sectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GetUMPStx.default_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefault_section([NotNull] GetUMPStx.Default_sectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GetUMPStx.idxEqId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdxEqId([NotNull] GetUMPStx.IdxEqIdContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>simpleEq</c>
	/// labeled alternative in <see cref="GetUMPStx.kvEq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleEq([NotNull] GetUMPStx.SimpleEqContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>idxEq</c>
	/// labeled alternative in <see cref="GetUMPStx.kvEq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdxEq([NotNull] GetUMPStx.IdxEqContext context);
}
